<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Semilla de códigos INS (Codex Alimentarius) más comunes en alimentos
 * envasados argentinos. Se almacena en la DB principal de Ophi.
 *
 * Para agregar un código nuevo: insertarlo acá y re-correr el seeder,
 * o insertarlo directo via tinker / admin UI futuro.
 */
class InsCodesSeeder extends Seeder
{
    public function run(): void
    {
        $codes = [
            // ── Colorantes (1xx) ──────────────────────────────────────────
            ['code' => '100',  'nombre' => 'curcumina',                              'categoria' => 'colorante'],
            ['code' => '101',  'nombre' => 'riboflavina',                             'categoria' => 'colorante'],
            ['code' => '102',  'nombre' => 'tartrazina',                              'categoria' => 'colorante'],
            ['code' => '104',  'nombre' => 'amarillo de quinoleína',                  'categoria' => 'colorante'],
            ['code' => '110',  'nombre' => 'amarillo ocaso (sunset yellow)',          'categoria' => 'colorante'],
            ['code' => '120',  'nombre' => 'cochinilla (carmín)',                     'categoria' => 'colorante'],
            ['code' => '122',  'nombre' => 'azorrubina (carmoisina)',                 'categoria' => 'colorante'],
            ['code' => '123',  'nombre' => 'amaranto',                                'categoria' => 'colorante'],
            ['code' => '124',  'nombre' => 'rojo ponceau 4R',                         'categoria' => 'colorante'],
            ['code' => '127',  'nombre' => 'eritrosina',                              'categoria' => 'colorante'],
            ['code' => '129',  'nombre' => 'rojo allura AC',                          'categoria' => 'colorante'],
            ['code' => '131',  'nombre' => 'azul patente V',                          'categoria' => 'colorante'],
            ['code' => '132',  'nombre' => 'indigotina (índigo carmín)',              'categoria' => 'colorante'],
            ['code' => '133',  'nombre' => 'azul brillante FCF',                      'categoria' => 'colorante'],
            ['code' => '140',  'nombre' => 'clorofilas',                              'categoria' => 'colorante'],
            ['code' => '141',  'nombre' => 'complejos cúpricos de clorofilas',        'categoria' => 'colorante'],
            ['code' => '150a', 'nombre' => 'caramelo natural',                        'categoria' => 'colorante'],
            ['code' => '150b', 'nombre' => 'caramelo sulfito cáustico',              'categoria' => 'colorante'],
            ['code' => '150c', 'nombre' => 'caramelo amoniaco',                       'categoria' => 'colorante'],
            ['code' => '150d', 'nombre' => 'caramelo sulfito amoniaco',              'categoria' => 'colorante'],
            ['code' => '151',  'nombre' => 'negro brillante BN',                      'categoria' => 'colorante'],
            ['code' => '160a', 'nombre' => 'betacaroteno',                            'categoria' => 'colorante'],
            ['code' => '160b', 'nombre' => 'achiote (annatto)',                       'categoria' => 'colorante'],
            ['code' => '160c', 'nombre' => 'oleorresina de páprika',                  'categoria' => 'colorante'],
            ['code' => '160d', 'nombre' => 'licopeno',                                'categoria' => 'colorante'],
            ['code' => '160e', 'nombre' => 'beta-apo-8-carotenal',                   'categoria' => 'colorante'],
            ['code' => '161b', 'nombre' => 'luteína',                                 'categoria' => 'colorante'],
            ['code' => '162',  'nombre' => 'betanina (rojo de remolacha)',            'categoria' => 'colorante'],
            ['code' => '163',  'nombre' => 'antocianinas',                            'categoria' => 'colorante'],
            ['code' => '170',  'nombre' => 'carbonato de calcio',                     'categoria' => 'colorante'],
            ['code' => '171',  'nombre' => 'dióxido de titanio',                      'categoria' => 'colorante'],
            ['code' => '172',  'nombre' => 'óxidos e hidróxidos de hierro',           'categoria' => 'colorante'],

            // ── Conservantes (2xx) ────────────────────────────────────────
            ['code' => '200',  'nombre' => 'ácido sórbico',                           'categoria' => 'conservante'],
            ['code' => '202',  'nombre' => 'sorbato de potasio',                      'categoria' => 'conservante'],
            ['code' => '203',  'nombre' => 'sorbato de calcio',                       'categoria' => 'conservante'],
            ['code' => '210',  'nombre' => 'ácido benzoico',                          'categoria' => 'conservante'],
            ['code' => '211',  'nombre' => 'benzoato de sodio',                       'categoria' => 'conservante'],
            ['code' => '212',  'nombre' => 'benzoato de potasio',                     'categoria' => 'conservante'],
            ['code' => '213',  'nombre' => 'benzoato de calcio',                      'categoria' => 'conservante'],
            ['code' => '220',  'nombre' => 'dióxido de azufre',                       'categoria' => 'conservante'],
            ['code' => '221',  'nombre' => 'sulfito de sodio',                        'categoria' => 'conservante'],
            ['code' => '222',  'nombre' => 'bisulfito de sodio',                      'categoria' => 'conservante'],
            ['code' => '223',  'nombre' => 'metabisulfito de sodio',                  'categoria' => 'conservante'],
            ['code' => '224',  'nombre' => 'metabisulfito de potasio',                'categoria' => 'conservante'],
            ['code' => '226',  'nombre' => 'sulfito de calcio',                       'categoria' => 'conservante'],
            ['code' => '227',  'nombre' => 'bisulfito de calcio',                     'categoria' => 'conservante'],
            ['code' => '228',  'nombre' => 'bisulfito de potasio',                    'categoria' => 'conservante'],
            ['code' => '234',  'nombre' => 'nisina',                                  'categoria' => 'conservante'],
            ['code' => '235',  'nombre' => 'natamicina (pimaricina)',                 'categoria' => 'conservante'],
            ['code' => '249',  'nombre' => 'nitrito de potasio',                      'categoria' => 'conservante'],
            ['code' => '250',  'nombre' => 'nitrito de sodio',                        'categoria' => 'conservante'],
            ['code' => '251',  'nombre' => 'nitrato de sodio',                        'categoria' => 'conservante'],
            ['code' => '252',  'nombre' => 'nitrato de potasio',                      'categoria' => 'conservante'],
            ['code' => '260',  'nombre' => 'ácido acético',                           'categoria' => 'conservante'],
            ['code' => '261',  'nombre' => 'acetato de potasio',                      'categoria' => 'conservante'],
            ['code' => '262',  'nombre' => 'acetato de sodio',                        'categoria' => 'conservante'],
            ['code' => '270',  'nombre' => 'ácido láctico',                           'categoria' => 'conservante'],
            ['code' => '280',  'nombre' => 'ácido propiónico',                        'categoria' => 'conservante'],
            ['code' => '281',  'nombre' => 'propionato de sodio',                     'categoria' => 'conservante'],
            ['code' => '282',  'nombre' => 'propionato de calcio',                    'categoria' => 'conservante'],
            ['code' => '283',  'nombre' => 'propionato de potasio',                   'categoria' => 'conservante'],

            // ── Antioxidantes / acidulantes (3xx) ────────────────────────
            ['code' => '296',  'nombre' => 'ácido málico',                            'categoria' => 'acidulante'],
            ['code' => '300',  'nombre' => 'ácido ascórbico',                         'categoria' => 'antioxidante'],
            ['code' => '301',  'nombre' => 'ascorbato de sodio',                      'categoria' => 'antioxidante'],
            ['code' => '302',  'nombre' => 'ascorbato de calcio',                     'categoria' => 'antioxidante'],
            ['code' => '304',  'nombre' => 'palmitato de ascorbilo',                  'categoria' => 'antioxidante'],
            ['code' => '306',  'nombre' => 'tocoferoles',                             'categoria' => 'antioxidante'],
            ['code' => '307',  'nombre' => 'alfa-tocoferol',                          'categoria' => 'antioxidante'],
            ['code' => '308',  'nombre' => 'gamma-tocoferol',                         'categoria' => 'antioxidante'],
            ['code' => '309',  'nombre' => 'delta-tocoferol',                         'categoria' => 'antioxidante'],
            ['code' => '310',  'nombre' => 'galato de propilo',                       'categoria' => 'antioxidante'],
            ['code' => '311',  'nombre' => 'galato de octilo',                        'categoria' => 'antioxidante'],
            ['code' => '312',  'nombre' => 'galato de dodecilo',                      'categoria' => 'antioxidante'],
            ['code' => '315',  'nombre' => 'ácido eritórbico',                        'categoria' => 'antioxidante'],
            ['code' => '316',  'nombre' => 'eritorbato de sodio',                     'categoria' => 'antioxidante'],
            ['code' => '319',  'nombre' => 'butilhidroxiquinona terciaria (TBHQ)',    'categoria' => 'antioxidante'],
            ['code' => '320',  'nombre' => 'butilhidroxianisol (BHA)',                'categoria' => 'antioxidante'],
            ['code' => '321',  'nombre' => 'butilhidroxitolueno (BHT)',               'categoria' => 'antioxidante'],
            ['code' => '322',  'nombre' => 'lecitina',                                'categoria' => 'emulsionante'],
            ['code' => '325',  'nombre' => 'lactato de sodio',                        'categoria' => 'humectante'],
            ['code' => '326',  'nombre' => 'lactato de potasio',                      'categoria' => 'humectante'],
            ['code' => '327',  'nombre' => 'lactato de calcio',                       'categoria' => 'humectante'],
            ['code' => '330',  'nombre' => 'ácido cítrico',                           'categoria' => 'acidulante'],
            ['code' => '331',  'nombre' => 'citrato de sodio',                        'categoria' => 'acidulante'],
            ['code' => '332',  'nombre' => 'citrato de potasio',                      'categoria' => 'acidulante'],
            ['code' => '333',  'nombre' => 'citrato de calcio',                       'categoria' => 'acidulante'],
            ['code' => '334',  'nombre' => 'ácido tartárico',                         'categoria' => 'acidulante'],
            ['code' => '335',  'nombre' => 'tartrato de sodio',                       'categoria' => 'acidulante'],
            ['code' => '336',  'nombre' => 'tartrato de potasio',                     'categoria' => 'acidulante'],
            ['code' => '337',  'nombre' => 'tartrato doble de sodio y potasio',       'categoria' => 'acidulante'],
            ['code' => '338',  'nombre' => 'ácido fosfórico',                         'categoria' => 'acidulante'],
            ['code' => '339',  'nombre' => 'fosfato de sodio',                        'categoria' => 'estabilizante'],
            ['code' => '340',  'nombre' => 'fosfato de potasio',                      'categoria' => 'estabilizante'],
            ['code' => '341',  'nombre' => 'fosfato de calcio',                       'categoria' => 'estabilizante'],
            ['code' => '343',  'nombre' => 'fosfato de magnesio',                     'categoria' => 'estabilizante'],
            ['code' => '350',  'nombre' => 'malato de sodio',                         'categoria' => 'acidulante'],
            ['code' => '351',  'nombre' => 'malato de potasio',                       'categoria' => 'acidulante'],

            // ── Espesantes / estabilizantes (4xx) ────────────────────────
            ['code' => '400',  'nombre' => 'ácido algínico',                          'categoria' => 'espesante'],
            ['code' => '401',  'nombre' => 'alginato de sodio',                       'categoria' => 'espesante'],
            ['code' => '402',  'nombre' => 'alginato de potasio',                     'categoria' => 'espesante'],
            ['code' => '404',  'nombre' => 'alginato de calcio',                      'categoria' => 'espesante'],
            ['code' => '405',  'nombre' => 'alginato de propilenglicol',              'categoria' => 'espesante'],
            ['code' => '406',  'nombre' => 'agar agar',                               'categoria' => 'espesante'],
            ['code' => '407',  'nombre' => 'carragenina',                             'categoria' => 'espesante'],
            ['code' => '410',  'nombre' => 'goma garrofín (algarrobo)',               'categoria' => 'espesante'],
            ['code' => '412',  'nombre' => 'goma guar',                               'categoria' => 'espesante'],
            ['code' => '413',  'nombre' => 'goma tragacanto',                         'categoria' => 'espesante'],
            ['code' => '414',  'nombre' => 'goma arábiga',                            'categoria' => 'espesante'],
            ['code' => '415',  'nombre' => 'goma xántica',                            'categoria' => 'espesante'],
            ['code' => '416',  'nombre' => 'goma karaya',                             'categoria' => 'espesante'],
            ['code' => '417',  'nombre' => 'goma tara',                               'categoria' => 'espesante'],
            ['code' => '418',  'nombre' => 'goma gelana',                             'categoria' => 'espesante'],
            ['code' => '420',  'nombre' => 'sorbitol',                                'categoria' => 'humectante'],
            ['code' => '421',  'nombre' => 'manitol',                                 'categoria' => 'humectante'],
            ['code' => '422',  'nombre' => 'glicerol',                                'categoria' => 'humectante'],
            ['code' => '440',  'nombre' => 'pectina',                                 'categoria' => 'espesante'],
            ['code' => '450',  'nombre' => 'difosfatos',                              'categoria' => 'estabilizante'],
            ['code' => '451',  'nombre' => 'trifosfatos',                             'categoria' => 'estabilizante'],
            ['code' => '452',  'nombre' => 'polifosfatos',                            'categoria' => 'estabilizante'],
            ['code' => '460',  'nombre' => 'celulosa',                                'categoria' => 'espesante'],
            ['code' => '461',  'nombre' => 'metilcelulosa',                           'categoria' => 'espesante'],
            ['code' => '464',  'nombre' => 'hidroxipropilmetilcelulosa',              'categoria' => 'espesante'],
            ['code' => '466',  'nombre' => 'carboximetilcelulosa sódica',             'categoria' => 'espesante'],
            ['code' => '471',  'nombre' => 'mono y diglicéridos de ácidos grasos',   'categoria' => 'emulsionante'],
            ['code' => '472a', 'nombre' => 'ésteres acéticos de mono y diglicéridos', 'categoria' => 'emulsionante'],
            ['code' => '472b', 'nombre' => 'ésteres lácticos de mono y diglicéridos', 'categoria' => 'emulsionante'],
            ['code' => '472c', 'nombre' => 'ésteres cítricos de mono y diglicéridos', 'categoria' => 'emulsionante'],
            ['code' => '472e', 'nombre' => 'ésteres diacetiltartáricos de mono y diglicéridos', 'categoria' => 'emulsionante'],
            ['code' => '473',  'nombre' => 'ésteres de sacarosa de ácidos grasos',   'categoria' => 'emulsionante'],
            ['code' => '476',  'nombre' => 'poliglicerol polirricinoleato',           'categoria' => 'emulsionante'],
            ['code' => '477',  'nombre' => 'ésteres de propilenglicol de ácidos grasos', 'categoria' => 'emulsionante'],
            ['code' => '481',  'nombre' => 'estearoil lactilato de sodio',            'categoria' => 'emulsionante'],
            ['code' => '482',  'nombre' => 'estearoil lactilato de calcio',           'categoria' => 'emulsionante'],
            ['code' => '491',  'nombre' => 'sorbitán monoestearato',                  'categoria' => 'emulsionante'],
            ['code' => '492',  'nombre' => 'sorbitán triestearato',                   'categoria' => 'emulsionante'],
            ['code' => '493',  'nombre' => 'sorbitán monolaurato',                    'categoria' => 'emulsionante'],
            ['code' => '494',  'nombre' => 'sorbitán monooleato',                     'categoria' => 'emulsionante'],
            ['code' => '495',  'nombre' => 'sorbitán monopalmitato',                  'categoria' => 'emulsionante'],

            // ── Potenciadores de sabor (6xx) ──────────────────────────────
            ['code' => '620',  'nombre' => 'ácido glutámico',                         'categoria' => 'potenciador'],
            ['code' => '621',  'nombre' => 'glutamato monosódico',                    'categoria' => 'potenciador'],
            ['code' => '622',  'nombre' => 'glutamato monopotásico',                  'categoria' => 'potenciador'],
            ['code' => '625',  'nombre' => 'glutamato de magnesio',                   'categoria' => 'potenciador'],
            ['code' => '627',  'nombre' => 'guanilato disódico',                      'categoria' => 'potenciador'],
            ['code' => '631',  'nombre' => 'inosinato disódico',                      'categoria' => 'potenciador'],
            ['code' => '635',  'nombre' => 'ribonucleótidos disódicos',               'categoria' => 'potenciador'],

            // ── Edulcorantes (9xx) ────────────────────────────────────────
            ['code' => '950',  'nombre' => 'acesulfame de potasio',                   'categoria' => 'edulcorante'],
            ['code' => '951',  'nombre' => 'aspartamo',                               'categoria' => 'edulcorante'],
            ['code' => '952',  'nombre' => 'ciclamato',                               'categoria' => 'edulcorante'],
            ['code' => '953',  'nombre' => 'isomaltitol',                             'categoria' => 'edulcorante'],
            ['code' => '954',  'nombre' => 'sacarina',                                'categoria' => 'edulcorante'],
            ['code' => '955',  'nombre' => 'sucralosa',                               'categoria' => 'edulcorante'],
            ['code' => '957',  'nombre' => 'taumatina',                               'categoria' => 'edulcorante'],
            ['code' => '959',  'nombre' => 'neohesperidina DC',                       'categoria' => 'edulcorante'],
            ['code' => '960',  'nombre' => 'glucósidos de esteviol (stevia)',         'categoria' => 'edulcorante'],
            ['code' => '961',  'nombre' => 'neotamo',                                 'categoria' => 'edulcorante'],
            ['code' => '962',  'nombre' => 'sal de aspartamo y acesulfame',           'categoria' => 'edulcorante'],
            ['code' => '965',  'nombre' => 'maltitol',                                'categoria' => 'edulcorante'],
            ['code' => '966',  'nombre' => 'lactitol',                                'categoria' => 'edulcorante'],
            ['code' => '967',  'nombre' => 'xilitol',                                 'categoria' => 'edulcorante'],
            ['code' => '968',  'nombre' => 'eritritol',                               'categoria' => 'edulcorante'],

            // ── Antiapelmazantes / agentes de recubrimiento ───────────────
            ['code' => '500',  'nombre' => 'carbonato de sodio',                      'categoria' => 'regulador de acidez'],
            ['code' => '501',  'nombre' => 'carbonato de potasio',                    'categoria' => 'regulador de acidez'],
            ['code' => '503',  'nombre' => 'carbonato de amonio',                     'categoria' => 'regulador de acidez'],
            ['code' => '504',  'nombre' => 'carbonato de magnesio',                   'categoria' => 'antiapelmazante'],
            ['code' => '509',  'nombre' => 'cloruro de calcio',                       'categoria' => 'estabilizante'],
            ['code' => '511',  'nombre' => 'cloruro de magnesio',                     'categoria' => 'estabilizante'],
            ['code' => '516',  'nombre' => 'sulfato de calcio',                       'categoria' => 'estabilizante'],
            ['code' => '551',  'nombre' => 'dióxido de silicio',                      'categoria' => 'antiapelmazante'],
            ['code' => '552',  'nombre' => 'silicato de calcio',                      'categoria' => 'antiapelmazante'],
            ['code' => '553',  'nombre' => 'silicato de magnesio',                    'categoria' => 'antiapelmazante'],
            ['code' => '554',  'nombre' => 'silicato de sodio y aluminio',            'categoria' => 'antiapelmazante'],
            ['code' => '570',  'nombre' => 'ácido esteárico',                         'categoria' => 'antiapelmazante'],
        ];

        DB::table('ins_codes')->insertOrIgnore($codes);
    }
}
